use_frameworks!

target 'ZYInfiniteLoopView_Example' do
  pod 'ZYInfiniteLoopView', :path => '../'
  
  pod 'SDWebImage'

  target 'ZYInfiniteLoopView_Tests' do
    inherit! :search_paths

    
  end
end
